name: "netlify deploy"
on:
  push:
    branches:
      - master
jobs:
  netlify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: "deploy to netlify"
      uses: netlify/actions/cli@6c34c3fcafc69ac2e1d6dbf226560329c6dfc51b
      with:
        args: deploy --dir=./site --message="$GITHUB_SHA" --prod
      env:
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
