name: "Test"
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-20.04, macos-10.15]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - id: set_var
      run: |
        content=$(jq -r .nixpkgs.url <./nix/sources.json)
        echo "::set-output name=nivSourcesJson::$content"
    - uses: cachix/install-nix-action@v16
      with:
        nix_path: ${{ format('nixpkgs={0}', steps.set_var.outputs.nivSourcesJson) }}
    - name: "Install Cachix"
      uses: cachix/cachix-action@v10
      with:
        name: niv
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: "Run tests"
      run: ./script/test
